Sprint 10
septenmale/ImageFeed pull request #4
Opened 2024-10-31 10:10 UTC by septenmale

2024-10-31 10:26 UTC, septenmale commented
Если есть возможность подскажите между прочим правильно ли я организовал структуру файлов. Имею ввиду поразкладывал файлы в группы. Понятно ли интуитивно что где лежит и за что отвечает. А то сущностей стало так много и хотелось бы как то интуитивно понятно их уместить. Не стал создавать отдельные файлы с протоколами, а прописал их в классах, чтобы уменьшить кол-во файлов. 

Может могли бы посоветовать какой-то материал об этом или только с опытом придет?

2024-10-31 13:13 UTC, Kirchberg requested changes

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/OAuth2Service.swift
> +//            }
Было бы хорошо удалять неиспользуемый код, это позволит сократить количество строк кода в файле, упростить чтение файла и сфокусировать на самом важном рабочем коде

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/OAuth2Service.swift
> +    //    }
Было бы хорошо также убрать

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/OAuth2Service.swift
> +    static let shared = OAuth2Service()
Было бы хорошо разделять код и оставлять между разными секциями кода одну пустую строку до и после, то есть:
```swift
import UIKit
import WebKit

final class OAuth2Service {
    
    static let shared = OAuth2Service()
    
    private init() {}
    
    // Другой код
    
}
```

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/OAuth2Service.swift
В коде было бы хорошо упорядочить между собой переменные и функции по фиксированному код-стайлу, который бы не отличался от файла к файлу. У себя на проекте я использую такой код-стайл, он мне позволяет в любом файле быстро и структурированно найти то, что я бы хотел.

Рекомендую прийти к такому код-стайлу, но это как захотите:

```swift
// MARK: - Public Types
// MARK: - Public Properties
// MARK: - Public Init
// MARK: - Public Methods

// MARK: - Internal Types
// MARK: - Internal Properties
// MARK: - Internal Init
// MARK: - Internal Methods
...
// MARK: - Private Types
// MARK: - Private Properties
// MARK: - Private Init
// MARK: - Private Methods

```

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/AuthViewController.swift
> +                let viewController = segue.destination as? WebViewViewController
В данном случае лучше не переносить let на новую строку, а оставить рядом с guard, то есть:
```swift
guard let viewController = ...
```

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/AuthViewController.swift
> +
Было бы хорошо убрать эту пустую строку

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/WebViewViewController.swift
> +    weak var delegate: WebViewViewContrrollerDelegate? // добавляю св-во делегата
Вот здесь есть опечатка в названии делегата, было бы хорошо ее поправить, для этого можно поставить подсветку синтаксиса, она позволяет подсвечивать такие ошибки прямо внутри Xcode, вот как ее включить (предварительно нужно поместить курсор в сам текст файла):

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/d47a0dec-b638-4bbc-9319-c23dc2147df8">

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/WebViewViewController.swift
> +    }
`WebViewConstants` не используется снаружи класса, было бы хорошо его пометить как `private`

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Auth/WebViewViewController.swift
> +            context: nil)
Было бы хорошо сделать вот такие отступы:
```swift
webView.addObserver(
    self,
    forKeyPath: #keyPath(WKWebView.estimatedProgress),
    options: .new,
    context: nil
)
```

Они позволяют легче читать перечисление в параметрах функции, а также добавлять новые параметры в будущем

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/Constants.swift
> +    static let defaultBaseURL = URL(string: "https://api.unsplash.com")
Молодец, что не сделал force unwrap 🔥

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/OAuth2TokenStorage.swift
Случайно продублировали класс, он есть в двух экзмеплярах, давай уберем этот?

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/OAuthTokenResponseBody.swift
Тоже случайно продублировали

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/URLSession+data.swift
Тоже продублированный класс :)

2024-10-31 13:13 UTC, Kirchberg commented on ImageFeed/NetworkService/OAuth2/OAuth2Service.swift
> +            handler(.failure(NetworkError.urlSessionError))
⚠️ Вот здесь необходимо также залогировать ошибку при помощи `print(...)` по условиям пункта задания 12

2024-10-31 13:22 UTC, Kirchberg commented
> Если есть возможность подскажите между прочим правильно ли я организовал структуру файлов. Имею ввиду поразкладывал файлы в группы. Понятно ли интуитивно что где лежит и за что отвечает. А то сущностей стало так много и хотелось бы как то интуитивно понятно их уместить. Не стал создавать отдельные файлы с протоколами, а прописал их в классах, чтобы уменьшить кол-во файлов.
> 
> Может могли бы посоветовать какой-то материал об этом или только с опытом придет?

Привет, на данном этапе у тебя получилась хорошая структура проекта.

Обычно опытные разработчики придерживаются следующих советов по структуре файлов:
1. Используй Feature-based структуру: Вместо того чтобы группировать файлы по типу (например, «Models», «Views», «Controllers»), имеет смысл группировать по функциональности или экранам приложения, если оно не слишком маленькое. Например, если у тебя есть несколько экранов (скажем, «Профиль», «Настройки», «Главная»), ты можешь создать группы или папки Profile, Settings, Home, в каждой из которых будут все файлы, относящиеся к этим экранам. В таких папках можно уже создавать вложенные группы Models, Views, ViewModels и т.д.
2. Создай общие группы для Core и Shared элементов: Компоненты, которые используются в нескольких местах (например, сервисы, хелперы, утилиты и т.п.), лучше положить в общие группы Core или Shared. В эту категорию также могут входить Network, Extensions, Constants, Resources и т.п.

Хорошая практика: для протоколов, которые используются только в конкретных классах, вполне допустимо держать их в тех же файлах. Но если это протоколы, которые будут переиспользоваться или имплементироваться другими классами, то лучше вынести их в отдельные файлы и сгруппировать в папке Protocols.

Из материалов могу посоветовать следующее:
– https://stackoverflow.com/a/39945851
– https://github.com/futurice/ios-good-practices/issues/28


Обычно это и правда приходит не только с опытом, но и с тем насколько быстро и часто меняется твой проект. В командных проектах перед тем как начать работу было бы хорошо как раз проговорить этот момент, особенно, если этот проект только появляется, так вам будет проще работать вместе, а в старых командах этот процесс уж налажен и тебе уже сами подскажут как правильнее делать в рамках текущего проекта

Надеюсь мой ответ помог тебе ✨

2024-10-31 13:50 UTC, septenmale commented on ImageFeed/Auth/OAuth2Service.swift
> +//            }
Поправил

2024-10-31 13:51 UTC, septenmale commented on ImageFeed/Auth/OAuth2Service.swift
> +    //    }
Убрал

2024-10-31 13:51 UTC, septenmale commented on ImageFeed/Auth/OAuth2Service.swift
> +    static let shared = OAuth2Service()
Исправлено

2024-10-31 13:54 UTC, septenmale commented on ImageFeed/Auth/AuthViewController.swift
> +                let viewController = segue.destination as? WebViewViewController
Исправил

2024-10-31 14:02 UTC, septenmale commented on ImageFeed/Auth/WebViewViewController.swift
> +    weak var delegate: WebViewViewContrrollerDelegate? // добавляю св-во делегата
исправлено

2024-10-31 14:06 UTC, septenmale commented on ImageFeed/Auth/WebViewViewController.swift
> +            context: nil)
Сделано

2024-10-31 14:11 UTC, septenmale commented on ImageFeed/OAuth2TokenStorage.swift
у меня почему то другая структура в локальном файле и в том что видите вы.
надеюсь со вторым коммитом исправится

2024-10-31 14:11 UTC, septenmale commented on ImageFeed/OAuthTokenResponseBody.swift
такая же проблема

2024-10-31 14:11 UTC, septenmale commented on ImageFeed/URLSession+data.swift
и снова

2024-10-31 14:17 UTC, septenmale commented on ImageFeed/NetworkService/OAuth2/OAuth2Service.swift
> +            handler(.failure(NetworkError.urlSessionError))
ошибка залакирована

2024-10-31 14:19 UTC, septenmale commented on ImageFeed/Auth/OAuth2Service.swift
оформил интерфейсы но несколько в другом стиле

2024-11-01 07:42 UTC, Kirchberg approved these changes

2024-11-01 08:12 UTC, merged