Sprint 11
septenmale/ImageFeed pull request #5
Opened 2024-11-19 11:04 UTC by septenmale

2024-11-19 11:08 UTC, septenmale commented
Небольшой вопрос:

знаю, что оставлять комментарии в коде для процессов, которые интуитивно понятно это плохой тон, но что, если оставлять их чисто для себя, пока работаешь над проектом? Чтобы понимать основную логику и припоминать в процессе работы. Ведь модуль длинный и после определенного времени уже не очень помню что я делал в этом месте и зачем.

Имеет ли такая затея право на жизнь?)

2024-11-20 09:04 UTC, Kirchberg commented
> Небольшой вопрос:
> 
> знаю, что оставлять комментарии в коде для процессов, которые интуитивно понятно это плохой тон, но что, если оставлять их чисто для себя, пока работаешь над проектом? Чтобы понимать основную логику и припоминать в процессе работы. Ведь модуль длинный и после определенного времени уже не очень помню что я делал в этом месте и зачем.
> 
> Имеет ли такая затея право на жизнь?)

Да, такая затея имеет право на жизнь. На самом деле, комментарии в коде могут быть довольно полезными, особенно когда работаешь над сложными или длительными проектами. Вот почему стоит оставлять комментарии для самого себя:
- Когда возвращаешься к коду спустя некоторое время, комментарии помогают быстро восстановить контекст и понять, какие задачи выполняет каждый участок кода.
- Если алгоритм или логика задачи сложны и не сразу очевидны, комментарии могут быть незаменимыми для понимания работы кода.
- Если в проект вовлекаются другие разработчики, комментарии могут помочь им быстрее вникнуть в логику и поддерживать код в будущем.

Однако несколько рекомендаций все же стоит учитывать:
- Используйте комментарии для объяснения сложных частей кода, а не для простых вещей.
- Регулярно пересматривай и актуализируй комментарии, чтобы они оставались релевантными.

2024-11-20 09:32 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. При попытке войти в аккаунт приложение не переходит на страницу с фотографиями и выдает в логах ошибку: `[ProfileService]: Error while fetching profile: The data couldn’t be read because it is missing. Failed to fetch profile: The data couldn’t be read because it is missing.` и `Decoding Error: The data couldn’t be read because it is missing., Data: …`, [см. видео](https://disk.yandex.ru/i/FNCW7WMuX_HYQw). По этой причине не могу проверить один из пунктов задания 5.
2. В соответствии с пунктом задания 10 необходимо привести названия на русский язык. Можно также попробовать добавить локализацию, в таком случае у нас для русского и английского будут свои строки, в ином случае половина приложения на русском, а другая на английском.

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/AppDelegate.swift
> +        return sceneConfiguration
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/AppDelegate.swift
> +//        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
В данном случае код уже не понадобится и его было бы хорошо убрать

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/Assets.xcassets/Icons/placeholder.imageset/placeholder.jpeg
Было бы хорошо также добавить иконки с разрешением x2 и x3, так как они используются в современных iPhone и в ином случае будут выглядеть искаженно или «зашакалено»
<img width="399" alt="image" src="https://github.com/user-attachments/assets/4e5cdcfb-6d27-462c-93f6-d82cce60dbd9">

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/Auth/AuthViewController.swift
> +        UIBlockingProgressHud.show() // ProgressHUD.animate()
Такие комментарии было бы хорошо удалить или сразу назвать так функции

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/Auth/WebViewViewController.swift
> +//        )
Код старого API нужно удалять, так как он больше не потребуется :)

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/NetworkService/OAuth2/OAuth2Service.swift
> +}
Классно 🔥

2024-11-20 09:32 UTC, Kirchberg commented on ImageFeed/NetworkService/ProfileService/ProfileImageService.swift
> +            }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-11-20 11:18 UTC, septenmale commented
как оказалось ошибка была в том, что я ожидал от сервера bio профиля, а оно, в свою очередь, необязательно для заполнения. После этого тестировал, входя в новый аккаунт без bio, и никаких ошибок не было

2024-11-20 11:46 UTC, septenmale commented on ImageFeed/Assets.xcassets/Icons/placeholder.imageset/placeholder.jpeg
Добавил дополнительно 2х и 3х иконки

2024-11-20 11:46 UTC, septenmale commented on ImageFeed/Auth/AuthViewController.swift
> +        UIBlockingProgressHud.show() // ProgressHUD.animate()
удалил комментарии

2024-11-20 11:46 UTC, septenmale commented on ImageFeed/Auth/WebViewViewController.swift
> +//        )
удалил старый код

2024-11-20 11:47 UTC, septenmale commented on ImageFeed/NetworkService/ProfileService/ProfileImageService.swift
> +            }
поправил отступы

2024-11-21 08:50 UTC, Kirchberg commented
Привет, к сожалению все та же ошибка, не смог войти в аккаунт, предоставил полный лог ниже:
```
Token response: LdD957iogoKbL1453WJO-hpPjmLnYaRGlzWUCuOZock
Token received and saved: LdD957iogoKbL1453WJO-hpPjmLnYaRGlzWUCuOZock
Profile request URL: https://api.unsplash.com/me
HTTP method: GET
Authorization header: Bearer LdD957iogoKbL1453WJO-hpPjmLnYaRGlzWUCuOZock
Decoding Error: The data couldn’t be read because it is missing., Data: {"id":"7otKKchRTAk","updated_at":"2024-11-21T08:46:28Z","username":"ypios","name":"Yandex","first_name":"Yandex","last_name":null,"twitter_username":null,"portfolio_url":null,"bio":null,"location":null,"links":{"self":"https://api.unsplash.com/users/ypios","html":"https://unsplash.com/@ypios","photos":"https://api.unsplash.com/users/ypios/photos","likes":"https://api.unsplash.com/users/ypios/likes","portfolio":"https://api.unsplash.com/users/ypios/portfolio","following":"https://api.unsplash.com/users/ypios/following","followers":"https://api.unsplash.com/users/ypios/followers"},"profile_image":{"small":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=32\u0026h=32","medium":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=64\u0026h=64","large":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=128\u0026h=128"},"instagram_username":null,"total_collections":0,"total_likes":483,"total_photos":0,"total_promoted_photos":0,"total_illustrations":0,"total_promoted_illustrations":0,"accepted_tos":false,"for_hire":false,"social":{"instagram_username":null,"portfolio_url":null,"twitter_username":null,"paypal_email":null},"followed_by_user":false,"photos":[],"badge":null,"tags":{"custom":[],"aggregated":[]},"followers_count":0,"following_count":0,"allow_messages":true,"numeric_id":12349835,"downloads":0,"meta":{"index":false},"uid":"7otKKchRTAk","confirmed":true,"uploads_remaining":10,"unlimited_uploads":false,"email":"ypios@pm.me","dmca_verification":"unverified","unread_in_app_notifications":false,"unread_highlight_notifications":false}
[ProfileService]: Error while fetching profile: The data couldn’t be read because it is missing.
Failed to fetch profile: The data couldn’t be read because it is missing.
Profile request URL: https://api.unsplash.com/me
HTTP method: GET
Authorization header: Bearer LdD957iogoKbL1453WJO-hpPjmLnYaRGlzWUCuOZock
Decoding Error: The data couldn’t be read because it is missing., Data: {"id":"7otKKchRTAk","updated_at":"2024-11-21T08:46:28Z","username":"ypios","name":"Yandex","first_name":"Yandex","last_name":null,"twitter_username":null,"portfolio_url":null,"bio":null,"location":null,"links":{"self":"https://api.unsplash.com/users/ypios","html":"https://unsplash.com/@ypios","photos":"https://api.unsplash.com/users/ypios/photos","likes":"https://api.unsplash.com/users/ypios/likes","portfolio":"https://api.unsplash.com/users/ypios/portfolio","following":"https://api.unsplash.com/users/ypios/following","followers":"https://api.unsplash.com/users/ypios/followers"},"profile_image":{"small":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=32\u0026h=32","medium":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=64\u0026h=64","large":"https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3\u0026crop=faces\u0026fit=crop\u0026w=128\u0026h=128"},"instagram_username":null,"total_collections":0,"total_likes":483,"total_photos":0,"total_promoted_photos":0,"total_illustrations":0,"total_promoted_illustrations":0,"accepted_tos":false,"for_hire":false,"social":{"instagram_username":null,"portfolio_url":null,"twitter_username":null,"paypal_email":null},"followed_by_user":false,"photos":[],"badge":null,"tags":{"custom":[],"aggregated":[]},"followers_count":0,"following_count":0,"allow_messages":true,"numeric_id":12349835,"downloads":0,"meta":{"index":false},"uid":"7otKKchRTAk","confirmed":true,"uploads_remaining":10,"unlimited_uploads":false,"email":"ypios@pm.me","dmca_verification":"unverified","unread_in_app_notifications":false,"unread_highlight_notifications":false}
[ProfileService]: Error while fetching profile: The data couldn’t be read because it is missing.
Failed to fetch profile: The data couldn’t be read because it is missing.
```

2024-11-21 11:45 UTC, septenmale commented
Действительно! Как оказалось фамилия тоже не обязательная. А я сколько не проверял не мог обнаружить у себя данную ошибку так как заполнил профиль полностью. Исправил ошибку и держу кулачки, чтобы все запостилось 

Пусть 2 дня всяческих исправлений будут мне уроком за то, что невнимательно читал API ))

2024-11-22 09:37 UTC, Kirchberg commented
Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании!

2024-11-22 09:40 UTC, merged