Sprint 13
septenmale/ImageFeed pull request #7
Opened 2024-12-17 12:26 UTC by septenmale

2024-12-17 12:27 UTC, septenmale commented
Буду рад любым замечаниям по поводу того как можно улучшить свою работу. Чтобы так сказать было не стыдно показать другим разработчикам. Ведь это по сути конец данного модуля

2024-12-17 14:42 UTC, septenmale commented
Добавил небольшие исправления в последнем коммите.

2024-12-17 16:56 UTC, NaR0RoW requested changes
Тест `testPresenterCallsUpdateProfileDetails` падает

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    func code(from url: URL) -> String?
В общем случае функция предполагает выполнение определенного действия, поэтому название этих методов можно немного улучшить, например:
`func createAuthURLRequest() -> URLRequest?`
Хотя в данном случае я бы воспользовался вычисляемой переменной:
```
var authURLRequest: URLRequest? {
   guard let url = authURL() else { return nil }
   return URLRequest(url: url)
}
```

Для второго метода можно что-то вроде:
`func getCode(from url: URL) -> String?`

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    func authURL() -> URL? {
Лучше сделать вычисляемой переменной или изменить название метода на `createAuthURL() -> URL?`

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    let configuration: AuthConfiguration
Поле можно сделать приватным

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +            print("[AuthHelper]: [authRequest] - invalid auth URL")
Можно сейчас ничего не исправлять, принтов будет достаточно для обработок ошибок, но на будущее лучше [логировать ошибки](https://habr.com/ru/companies/agima/articles/821515/)

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Auth/WebViewPresenter.swift
> +    /// - Description: Определяет, какое значение прогресса задать для progressView и когда его скрывать
Такие комментарии в коде лучше не оставлять. Из названия функции и так понятно, за что она отвечает. Может быть сейчас немного рано, но советую в будущем прочитать книги Роберта Мартина, а именно "Чистый код" (в целом уже можно начать читать на досуге) и "Чистая архитектура" (лучше после некоторого коммерческого опыта). Конкретно про комментарии можно [тут](https://www.baeldung.com/cs/clean-code-comments) почитать. Это касается большинства комментариев в коде

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/AuthConfiguration.swift
> +    static let defaultBaseURL = URL(string: "https://api.unsplash.com")! //TODO: подумать про форс
Можно поправить `TODO`

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +         }
Код поехал

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/ImagesList/ImagesListViewPresenter.swift
> +
Лишний перенос строки

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Profile/ProfileViewController.swift
> +    }
Код поехал

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Profile/ProfileViewController.swift
> +     descriptionLabel.accessibilityIdentifier = "descriptionLabel"
Можно где вьюхи создаешь индификаторы указывать

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/Splash/SplashViewController.swift
>  class SplashViewController: UIViewController {
Класс можно пометить как `final`

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeed/TapBar/TapBarController.swift
> +        ) as! ImagesListViewController
Давай не будем использовать force unwrapp

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +        sleep(20)
Очень уж большое ожидание. И можно не делать тут sleep на 20 секунд, а ждать, пока появится `app.buttons["Authenticate"].tap()`, т.к. так будет быстрее

2024-12-17 16:56 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +        sleep(10)
Лучше не использовать `sleep` так часто. Тесты обычно на удаленных машинках гоняют. Представь, если в компании, условно, перед релизом приложения нужно прогнать 1000 тестов, а в каждом тесте будет слипов на 10 секунд. Мы только этих слипов будем ждать: `1000*10/60/60=3` часа, и это без учета остальной части тестов

2024-12-17 16:59 UTC, NaR0RoW commented
Что еще можно поправить:

1. Картинки на главное ленте низкого качества:

<img width="440" alt="Screenshot 2024-12-17 at 19 57 30" src="https://github.com/user-attachments/assets/08ab1718-97ae-4321-ae2e-01bb5a1cc125" />

2. Заглушка при загрузке картинки выглядит не совсем точно:

<img width="438" alt="Screenshot 2024-12-17 at 19 57 42" src="https://github.com/user-attachments/assets/5e885ebc-7c2b-45c3-a4f5-e22344015280" />

2024-12-18 10:25 UTC, septenmale commented
Изменил тест testProfile с тем, чтобы он проверял наличие персональных данных вместо существование лейблов. Специально оставляю пустое место для тестовых значений так же как и с логином и паролем.
Так же добавил проверку на существование кнопки Войти.

Относительно теста testAuth действительно не знаю в чем проблема так как у меня несколько раз подряд входило без проблем каких либо. Могли бы вы глянуть что в этот момент происходит на экране симулятора? Может выскакивают соглашение на куки или еще какое то окно, что может перекрыть поля ввода. У меня помню один раз выскочило какое то окно от эпл связанный с эмоджи и тест провалился, помог перезапуск теста и с тех пор таких проблем не было ни разу.

строчку же app.tap() добавил специально с тем чтобы перейти к полю ввода пароля от поля ввода логина вместо swipeUp() предложенного в решении так как после него почему то перехода не случалось.

2024-12-19 09:28 UTC, NaR0RoW commented
Привет ✋🏻 
Перепроверил тесты несколько раз на разных устройствах: все работает должным образом. Проблемы есть, если запускать тест первый раз на устройстве или же первый раз заходить под учеткой в Unsplash. В первом случае тест упадает, т.к. не сможет вбить email пользователя из-за подсказок по клавиатуре от Apple, а во второй раз из-за дополнительного окна с подтверждением входа от Unsplash. Это corner кейсы, которые в данном случае можно не обрабатывать, но в целом, в реальных приложениях о таком нужно думать. 
Отличная работа, с радостью ее зачту. Удачи дальше!

2024-12-19 16:22 UTC, merged